version: '2.2'
services:

  db:
    image: postgres
    ports:
      - "127.0.0.1:5432:5432"
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: walletdb
    volumes:
      - ./data/wallet/server/dbdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
      - 5005:5005
    environment:
      ACTIVE_PROFILE: default
      JVM_OPTS: -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=5005
    depends_on:
      db:
        condition: service_healthy