version: '2.2'
services:

  db:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: walletdb
    volumes:
      - ./server/data/dbdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  server:
    build:
      context: .
      dockerfile: Dockerfile-server
    ports:
      - 8080:8080
      - 8081:8081
      - 5005:5005
    environment:
      ACTIVE_PROFILE: docker
      JVM_OPTS: -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=5005
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "http://localhost:8081/management/health"]
      interval: 10s
      timeout: 5s
      retries: 10

  client:
    build:
      context: .
      dockerfile: client/Dockerfile
    environment:
      ACTIVE_PROFILE: docker
      USER_AMOUNT: 3
      CONCURRENT_THREADS_PER_USER: 2
      ROUNDS_PER_THREAD: 4
    depends_on:
      server:
        condition: service_healthy
