spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/walletdb
    username: postgres
    password: postgres
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        temp:
          use_jdbc_metadata_defaults: false
        hibernate:
          ddl-auto: validate
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    open-in-view: false

management:
  server:
    port: 8081
  endpoints:
    web:
      base-path: /management
      exposure:
        include: '*'

---
spring.profiles: docker
spring.datasource.url: jdbc:postgresql://db:5432/walletdb
