spring:
  datasource:
    url: jdbc:postgresql://localhost:5435/walletdb
    username: postgres
    password: root
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        temp:
          use_jdbc_metadata_defaults: false
        hibernate:
          ddl-auto: validate
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    open-in-view: false